# syntax=docker/dockerfile:1
FROM apache/airflow:2.6.3-python3.10

USER airflow

RUN --mount=type=cache,target=~/.cache/pip \
	pip install --upgrade pip && \
	pip install --no-cache-dir \
	"apache-airflow==2.6.3" \
	"apache-airflow-providers-dbt-cloud==3.3.0" \
	"apache-airflow-providers-postgres==5.5.1" \
	"astronomer-cosmos[dbt-postgres]==1.2.5" \
	"dbt-core==1.5.6" \
	"dbt-postgres==1.5.6" \
	"psycopg2-binary==2.9.6"
